package demo.addressList.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.MultiLanguage;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@MultiLanguage
@ExtensionAttribute(disable=true)
@Table(name = "addresslist")
public class Addresslist extends BaseDTO {
     @Id
     @Column
     @GeneratedValue
      private Long id;
    @MultiLanguageField
    @Column
      private String name;//姓名
    @Column
      private String phone;//联系方式
    @Column
      private String email;//邮箱
    @MultiLanguageField
      private String address;//地址
    @Column
      private String gender;//性别

    public Addresslist(){

    }
    public Addresslist( String name, String phone, String email, String address, String gender) {
        super();
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.gender = gender;
    }

    public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setAddress(String address){
         this.address = address;
     }

     public String getAddress(){
         return address;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     }
